#config file for PostgreSql
server:
port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Moretech5back
    username: postgres
    password: "%Eo434Xd"
  jpa.hibernate.ddl-auto: create